/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.mandla;
import net.mandla.TaskManager;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class TaskManagerTest {
    @Test void appHasAGreeting() {
        TaskManager classUnderTest = new TaskManager();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
